// Generated by CoffeeScript 1.9.2
(function() {
  var gulp;

  gulp = require('gulp');

  gulp.task('coffee', function() {
    var coffee, gutil;
    coffee = require('gulp-coffee');
    gutil = require('gulp-util');
    return gulp.src('src/coffee/*.coffee').pipe(coffee({
      bare: true
    })).on('error', gutil.log).pipe(gulp.dest('src/js/'));
  });

  gulp.task('browserify', function() {
    var browserify;
    browserify = require('browserify');
    return browserify('src/js/*.js');
  });

  gulp.task('default', ['coffee', 'browserify']);

}).call(this);
